/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Vsf234cfdRouteImport } from './routes/vsf234cfd'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTeamRouteImport } from './routes/_site.team'
import { Route as SiteReviewsRouteImport } from './routes/_site.reviews'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteEducationRouteImport } from './routes/_site.education'
import { Route as SiteAdventureRouteImport } from './routes/_site.adventure'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const Vsf234cfdRoute = Vsf234cfdRouteImport.update({
  id: '/vsf234cfd',
  path: '/vsf234cfd',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTeamRoute = SiteTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReviewsRoute = SiteReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEducationRoute = SiteEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdventureRoute = SiteAdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/vsf234cfd': typeof Vsf234cfdRoute
  '/about': typeof SiteAboutRoute
  '/adventure': typeof SiteAdventureRoute
  '/education': typeof SiteEducationRoute
  '/gallery': typeof SiteGalleryRoute
  '/reviews': typeof SiteReviewsRoute
  '/team': typeof SiteTeamRoute
}
export interface FileRoutesByTo {
  '/vsf234cfd': typeof Vsf234cfdRoute
  '/about': typeof SiteAboutRoute
  '/adventure': typeof SiteAdventureRoute
  '/education': typeof SiteEducationRoute
  '/gallery': typeof SiteGalleryRoute
  '/reviews': typeof SiteReviewsRoute
  '/team': typeof SiteTeamRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/vsf234cfd': typeof Vsf234cfdRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/adventure': typeof SiteAdventureRoute
  '/_site/education': typeof SiteEducationRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/reviews': typeof SiteReviewsRoute
  '/_site/team': typeof SiteTeamRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vsf234cfd'
    | '/about'
    | '/adventure'
    | '/education'
    | '/gallery'
    | '/reviews'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/vsf234cfd'
    | '/about'
    | '/adventure'
    | '/education'
    | '/gallery'
    | '/reviews'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/vsf234cfd'
    | '/_site/about'
    | '/_site/adventure'
    | '/_site/education'
    | '/_site/gallery'
    | '/_site/reviews'
    | '/_site/team'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  Vsf234cfdRoute: typeof Vsf234cfdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsf234cfd': {
      id: '/vsf234cfd'
      path: '/vsf234cfd'
      fullPath: '/vsf234cfd'
      preLoaderRoute: typeof Vsf234cfdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/team': {
      id: '/_site/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof SiteTeamRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reviews': {
      id: '/_site/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof SiteReviewsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/education': {
      id: '/_site/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof SiteEducationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/adventure': {
      id: '/_site/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof SiteAdventureRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAdventureRoute: typeof SiteAdventureRoute
  SiteEducationRoute: typeof SiteEducationRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteReviewsRoute: typeof SiteReviewsRoute
  SiteTeamRoute: typeof SiteTeamRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAdventureRoute: SiteAdventureRoute,
  SiteEducationRoute: SiteEducationRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteReviewsRoute: SiteReviewsRoute,
  SiteTeamRoute: SiteTeamRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  Vsf234cfdRoute: Vsf234cfdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
